[package]
name = "game-tree-strategy"
version = "0.1.0"
authors = ["Darren Tsung <darren.tsung@gmail.com>"]
edition = "2018"

[dependencies]
game-tree = { path = "../game-tree" }
monte-carlo-tree-search = { path = "../monte-carlo-tree-search" }
rand = "0.7.0"
